### ISSUE TITLE
Ocena projektu

### ISSUE THREAD

**Issue by W0J7AZ** [Piotr-Bednarek/DoodleJump#38]

**Comment by JOtworowski** [comment]
Projekt oceniam na 95%. 

Projekt w prawidłowy sposób wykorzystuje polimorfię, dziedziczenie, alokacje pamięci oraz github. Bez problemu uruchamia się z pliku .exe. Ilość przeciwników i powerupów postaci jest taka jak ustaliliśmy, animacje są płynne a gra działa bez zarzutu. Jedyne czego mi zabrakło to jakiejś progresji poziomu trudności. Mam wrażenie że wraz z postępem w grze nie zwiększa się ilość pojawiających się przeciwników. Ale poza tym projekt jest bardzo dobry i wykonany starannie.
